### ISSUE TITLE
PETSC ImportError

### ISSUE THREAD

**Issue by jhgroth** [LLNL/letop#27]
Hello,

thank your for sharing these great pieces of work. I am highly interested in working with the provided modules.

While trying out some of the examples. I always end up with an error while importing PETSc from firedrake.

This is for example the error that is produced when I start the bridge.py example:

> (ﬁredrake) JohnDoe@ubuntu-~/firedrake/bridgegpostmaster$ python3 bridge.py
firedrake:WARNING OMP_NUM_THREADS is not set or is set to a value greater than 1, we suggest setting OMP_NUM_THREADS
Traceback (most recent call last):
           File "bridge.py", line 15, in <module>
                  from pyMMAopt import MMASolver, ReducedInequality
           File "(home/JohnDoe/firedrake/lib/python3.8/site-packages/pyMMAopt/__init__.py", line 3, in <module>
                  from .mma_solver import MMASolver
           File "(home/JohnDoe/firedrake/lib/python3.8/site-packages/pyMMAopt/mma_solver.py", line 3, in <module>
                  from firedrake import (
ImportError: cannot import name 'PETSc' from 'firedrake' (/home/JohnDoe/firedrake/src/firedrake/firedrake/__init__.py)

Another error occurs when I start heat_exchanger.py:

Here the following line produces a PETSC import error:

> def print(x):
          return fd.PETSc.Sys.Print(x)

When I remove this line in heat_exchanger.py the code works fine.

Do you have any idea what could cause the 'PETSC ImportError' problem?

Thank you for your help.

**Comment by salazardetroya** [comment]
Just fixed it by updating pyMMAopt (https://github.com/LLNL/pyMMAopt/commit/be916ab5a45e5d33a0f807956d5fddba83a74061)

This issue is not of Letop, but pyMMAopt.
